---
title: "Enrichment"
author: "Shotaro Watanabe"
date: "2023/08/09 (Thu)"
output: html_document
---

```{r library, warning=FALSE}
library(dplyr)
library(ggplot2)
library(ggupset)
library(readr)
library(svglite)
library(stringr)
library(TDbasedUFE)
library(TDbasedUFEadv)
library(org.Hs.eg.db)
library(enrichR)
library(DOSE)
library(enrichplot)
library(clusterProfiler)
source("Functions.R", echo=FALSE)
source("Set_General_data.R", echo=FALSE)
```

```{r functions}
source("Functions.R", echo=FALSE)

get_genes_ID <- function(cell_type, Dataframe, Symbol=FALSE){
  
  PATH_TENSOR <- paste0("out_put_Tensor/", cell_type, "_Gene_tensor.rds")
  PATH_INDEX <- paste0("out_put_Tensor/", cell_type,"_index.rds")
  
  if (!file.exists(PATH_INDEX)) {
    stop(paste0(cell_type," HOSVD doesn't exist. Stop this R file Enrich.R."))
  }
  
  #-------(Get HOSVD Data)-------- 
  RAW_TENSOR <- readRDS(PATH_TENSOR)
  index <- readRDS(PATH_INDEX)
  genes <- unlist(tableFeatures(RAW_TENSOR, index)[, 1])
  genes <- genes[!is.na(genes)]
  entrez <- Dataframe$ID[ match(genes, Dataframe$Name) ]
  entrez <- entrez[!is.na(entrez)]
  entrez <- as.character(entrez)
  
  if(Symbol){
    return(genes)
  }else{
    return(entrez)
  }
}

```

```{r set data}
cell_type <- Cell_type_list[3]
Gene_df <- read.csv("Patient_Data/Gene_List.csv")

PATH_TENSOR <- paste0("out_put_Tensor/", cell_type, "_Gene_tensor.rds")
PATH_HOSDV <- paste0("out_put_Tensor/", cell_type,"_HOSVD.rds")
PATH_INDEX <- paste0("out_put_Tensor/", cell_type,"_index.rds")

if (!file.exists(PATH_INDEX)) {
  stop(paste0(cell_type," HOSVD doesn't exist. Stop this R file Enrich.R."))
}

#-------(Get HOSVD Data)-------- 
RAW_TENSOR <- readRDS(PATH_TENSOR)
HOSVD <- readRDS(PATH_HOSDV)
index <- readRDS(PATH_INDEX)
head( tableFeatures(RAW_TENSOR, index) )

genes <- unlist(tableFeatures(RAW_TENSOR, index)[, 1])
lack_range <- which(is.na(genes))
genes <- genes[-lack_range]
entrez <- Gene_df$ID[ match(genes, Gene_df$Name) ]
lack_range_ez <- which(is.na(entrez))
entrez <- entrez[-lack_range_ez]
entrez <- as.character(entrez)
univ <- Gene_df$ID[ match(RAW_TENSOR@feature, Gene_df$Name) ]
univ <- as.character(univ[!is.na(univ)])
pv <- unlist(tableFeatures(RAW_TENSOR, index)[, 2])
pv <- pv[-lack_range]
cat(cell_type)
```

```{r enrichR to cluster}

val_cell_types <- Cell_type_list[c(3:6,8,11)]
Gene_df <- read.csv("Patient_Data/Gene_List.csv")

Genes_List <- list()
for (i in val_cell_types) {
  Genes_List[[i]] <- get_genes_ID(i, Gene_df, Symbol = TRUE) 
}

mDIR <- "gmt/"
gmt_files <- paste0(mDIR, list.files(mDIR, pattern = ".gmt"))
gmt_files <- gmt_files[c(3:5,8)]

ENRICH <- list()
for (i in gmt_files) {
  print(i)
  enrichr_gmt <- read.gmt(i)

  try(ENRICH[[i]] <- compareCluster(Genes_List, fun="enricher", TERM2GENE=enrichr_gmt, 
                                    pvalueCutoff = 0.01, qvalueCutoff = 0.99)
    , silent = TRUE)
  
  if (i %in% gmt_files[c(1,2)]){
    ENRICH[[i]]@compareClusterResult$Description <- sub("(.*) \\(GO:\\d+\\)", "\\1", ENRICH[[i]]@compareClusterResult$Description)
    ENRICH[[i]]@compareClusterResult$ID <- sub(".*\\((GO:\\d+)\\)", "\\1", ENRICH[[i]]@compareClusterResult$ID)
  }
  
}

d <- list()
e <- list()
for (i in names(ENRICH)) {
    file_name <- gsub(".*/(\\w+)\\.gmt", "\\1", i)
    #write.csv(ENRICH[[i]]@compareClusterResult, 
    #          file=paste0("Enrich_Result/family_",file_name,".csv"))
    e[[i]] <- cnetplot(pairwise_termsim(ENRICH[[i]]), showCategory = 99, 
                    color.params = list(pie="Count", legend_n=5), 
                    cex.params = list(edge = TRUE), 
                    node_label = "all", layout="kk") + 
              ggtitle(paste0("       " ,file_name)) + 
              theme(plot.title = element_text(face = "bold", size = 22))
    d[[i]] <- dotplot(ENRICH[[i]], color = "pvalue") + 
            ggtitle(paste0(file_name) ) + 
            theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
            theme(plot.title = element_text(face = "bold", size = 18))
    ggsave(plot=d[[i]], filename=paste0("Graph/family_dot_", file_name, ".svg"), 
           width=9, h=6)
    ggsave(plot=e[[i]], filename=paste0("Graph/family_emap_", file_name, ".svg"), 
           width=10, h=6)
}

library(gridExtra)
ga <- grid.arrange(e[[1]],e[[2]],e[[3]], nrow=2)
gs <- grid.arrange(d[[1]],d[[2]],d[[3]], nrow=1)
library(ggpubr)
ga2 <- ggarrange(e[[1]],e[[2]],e[[3]], vjust = -2, font.label = list(size = 18), 
                 labels = list("a.","b.","c."))

ggsave(plot=ga, filename="Graph/family_Cnets.svg", 
       width=14, h=12)
ggsave(plot=gs, filename="Graph/family_dots.pdf", 
           width=20, h=6)

```

```{r List_GOBP}
val_cell_types <- Cell_type_list[c(3:6,8,11)]
Gene_df <- read.csv("Patient_Data/Gene_List.csv")

Genes_List <- list()
for (i in val_cell_types) {
  Genes_List[[i]] <- get_genes_ID(i, Gene_df, Symbol = TRUE) 
}

mDIR <- "gmt/"
gmt_files <- paste0(mDIR, list.files(mDIR, pattern = ".gmt"))
enrichr_gmt <- read.gmt(gmt_files[1])

GOBPs <- compareCluster(Genes_List, fun="enricher", TERM2GENE=enrichr_gmt,
                        pvalueCutoff = 0.99, qvalueCutoff = 0.99)

GOBPs@compareClusterResult$Description <- sub("(.*) \\(GO:\\d+\\)", "\\1", GOBPs@compareClusterResult$Description)
GOBPs@compareClusterResult$ID <- sub(".*\\((GO:\\d+)\\)", "\\1", GOBPs@compareClusterResult$ID)
GOBPs@compareClusterResult <- GOBPs@compareClusterResult[GOBPs@compareClusterResult$pvalue < 0.01,]

GOBPs <- pairwise_termsim(GOBPs)

e_BP <- emapplot(GOBPs, showCategory = 20, pie.params = list(pie="Count", legend_n=4), 
         cex.params = list(category_node=6, pie2axis=2), node_label = "group",
         layout.params = list(layout="kk")) + 
  ggtitle("GOBP for each cell type") + 
  theme(plot.title = element_text(face = "bold", size = 18))
d <- dotplot(GOBPs, showCategory=5, color = "pvalue") + 
        ggtitle("GOBP for each cell type") + 
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
        theme(plot.title = element_text(face = "bold", size = 18))

#ggsave(plot=e, filename=paste0("Graph/Go_BP_emap.svg"), 
#           width=6, h=6)
```

```{r List_GOCC}
Genes_List <- list()
for (i in val_cell_types) {
  Genes_List[[i]] <- get_genes_ID(i, Gene_df, Symbol = TRUE) 
}

mDIR <- "gmt/"
gmt_files <- paste0(mDIR, list.files(mDIR, pattern = ".gmt"))
enrichr_gmt <- read.gmt(gmt_files[2])

GOCCs <- compareCluster(Genes_List, fun="enricher", TERM2GENE=enrichr_gmt,
                        pvalueCutoff = 0.99, qvalueCutoff = 0.99)

GOCCs@compareClusterResult$Description <- sub("(.*) \\(GO:\\d+\\)", "\\1", GOCCs@compareClusterResult$Description)
GOCCs@compareClusterResult$ID <- sub(".*\\((GO:\\d+)\\)", "\\1", GOCCs@compareClusterResult$ID)
GOCCs@compareClusterResult <- GOCCs@compareClusterResult[GOCCs@compareClusterResult$pvalue < 0.01,]

GOCCs <- pairwise_termsim(GOCCs)

e_CC <- emapplot(GOCCs, showCategory = 20, pie.params = list(pie="Count", legend_n=4), 
         cex.params = list(category_node=1.3, pie2axis=1), node_label = "group") + 
  ggtitle("GOCC for each cell type") + 
  theme(plot.title = element_text(face = "bold", size = 18))
d <- dotplot(GOCCs, showCategory=10, color = "pvalue") + 
  ggtitle("GOCC for each cell type") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  theme(plot.title = element_text(face = "bold", size = 18))

#ggsave(plot=e, filename=paste0("Graph/GO_CC_emap.svg"), 
#           width=6, h=6)
```

```{r List_GOMF}
Genes_List <- list()
for (i in val_cell_types) {
  Genes_List[[i]] <- get_genes_ID(i, Gene_df, Symbol = TRUE) 
}

mDIR <- "gmt/"
gmt_files <- paste0(mDIR, list.files(mDIR, pattern = ".gmt"))
enrichr_gmt <- read.gmt(gmt_files[3])

GOMFs <- compareCluster(Genes_List, fun="enricher", TERM2GENE=enrichr_gmt,
                        pvalueCutoff = 0.99, qvalueCutoff = 0.99)

GOMFs@compareClusterResult$Description <- sub("(.*) \\(GO:\\d+\\)", "\\1", GOMFs@compareClusterResult$Description)
GOMFs@compareClusterResult$ID <- sub(".*\\((GO:\\d+)\\)", "\\1", GOMFs@compareClusterResult$ID)
GOMFs@compareClusterResult <- GOMFs@compareClusterResult[GOMFs@compareClusterResult$pvalue < 0.01,]

GOMFs <- pairwise_termsim(GOMFs)

e_MF <- emapplot(GOMFs, showCategory = 20, pie.params = list(pie="Count", legend_n=4), 
             cex.params = list(category_node=3, pie2axis=1), node_label = "group",
             layout.params = list(layout="kk")) + 
      ggtitle("GOMF for each cell type") + 
      theme(plot.title = element_text(face = "bold", size = 18))
d <- dotplot(GOMFs, showCategory=10, color = "pvalue") + 
      ggtitle("GOMF for each cell type") + 
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
      theme(plot.title = element_text(face = "bold", size = 18))


#ggsave(plot=e, filename=paste0("Graph/GO_MF_emap.svg"), 
#           width=6, h=6)
```

```{r List_KEGG_Human}
val_cell_types <- Cell_type_list[c(3:6,8,11)]
Gene_df <- read.csv("Patient_Data/Gene_List.csv")

Genes_List <- list()
for (i in val_cell_types) {
  Genes_List[[i]] <- get_genes_ID(i, Gene_df, Symbol = TRUE) 
}

mDIR <- "gmt/"
gmt_files <- paste0(mDIR, list.files(mDIR, pattern = ".gmt"))
enrichr_gmt <- read.gmt(gmt_files[4])

KEGGHs <- compareCluster(Genes_List, fun="enricher", TERM2GENE=enrichr_gmt,
                        pvalueCutoff = 0.99, qvalueCutoff = 0.99)

KEGGHs@compareClusterResult <- KEGGHs@compareClusterResult[KEGGHs@compareClusterResult$pvalue < 0.01,]

KEGGHs <- pairwise_termsim(KEGGHs)

e_KG <- emapplot(KEGGHs, showCategory = 21, pie.params = list(pie="Count", legend_n=4), 
             cex.params = list(category_node=3, pie2axis=1), node_label = "group",
             layout.params = list(layout="kk")) + 
  ggtitle("KEGG for each cell type") + 
  theme(plot.title = element_text(face = "bold", size = 18))
d <- dotplot(KEGGHs, showCategory=5, color = "pvalue") + 
        ggtitle("KEGGH for each cell type") + 
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
        theme(plot.title = element_text(face = "bold", size = 18))

#ggsave(plot=e, filename=paste0("Graph/KEGG_Human_emap.svg"), 
#           width=6, h=6)
```


```{r al_graph, warning=FALSE}
library(gridExtra)

pa <- list(e_BP, e_CC, e_MF, e_KG)

all_pa <- grid.arrange(grobs = pa, ncol=2, hline = c(1.5), 
                       padding = unit(2.5, "cm"))

ggsave(plot=all_pa, filename="Graph/All_cnet.svg", 
       width=12, h=12)

```


